### ISSUE TITLE
Foundation for Sites requires CDN URL not working as NPM module

### ISSUE THREAD

**Issue by wolfspider** [alachuacounty/Kiosk#1]
I'll start looking at this today and see what I can do about it. Normally, Foundation for Sites needs a URL Router and some setup in order for it to work. 

Documentation is located here:
https://foundation.zurb.com/sites/docs/

I'll be following that trying to figure out whats going on...

**Comment by youriwims** [comment]
Nice. I'll be working on this around 2p and will install the foundation-cli globally before I begin. Looking forward to learning more about the merge.

**Comment by wolfspider** [comment]
Just take a look at the /layouts/default.html and there you will see how all the pages are put together via components..the handlebars syntax that Foundation uses clearly defines various templating sections (i.e. {{> main-nav}}, {{> body}}). What can be done now is to take the content you've created already and place it into those sections without the CDN references. It should appear styled the same way.

**Comment by youriwims** [comment]
Okay, I'm going to do this for shelter.html & push it up in 10mins. Let me know if this is what you had in mind.

**Comment by youriwims** [comment]
I'm having issues with my Linux container right now. I'm most likely going to have to test this on Monday.

> Okay, I'm going to do this for shelter.html & push it up in 10mins. 
Let me know if this is what you had in mind.

**Comment by wolfspider** [comment]
@youriwims it looks like you have mastered the handlebars templating and have gone off and done quite a bit of work here with them. I would say this has been successfully achieved as well, closing issue
